version: '3'
services:
  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver
      0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
    environment:
      DEBUG: "true"
      DATABASE_URL: "postgres://local:local@db:5432/wedding-ac"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=wedding-ac
    ports:
      - "5432:5432"
