# Generated by Django 3.2.9 on 2023-03-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_party_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='reminder_sent',
        ),
    ]
